# Generated by Django 2.1.7 on 2019-03-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_position', to='accounts.Position'),
        ),
    ]
