# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-09 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='bob', max_length=140),
            preserve_default=False,
        ),
    ]
