# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-11 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='publications',
            new_name='users',
        ),
    ]
