# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-03-11 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190311_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='users',
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
